# Sales Agent Task
sales_highlights_task:
  description: >
    Each day, craft a short, compelling message about a new or notable development in {topic}
    and how it benefits investors on spin-world.site.
  expected_output: >
    One daily message every 5 minutes on {topic} could double your investment!
    Join us on spin-world.site to learn more!"
  agent: sales_agent

# Marketing Agent Task
marketing_engagement_task:
  description: >
    Use weekly trend analysis to send out teaser messages about {topic} or short polls/quizzes
    to engage the group, subtly promoting the platform's features.
  expected_output: >
    Messages like, "Discover the future of {topic} with us. Weekly insights on spin-world.site!"
    or a poll, e.g., "Which {topic} trend excites you most? A) AI B) Blockchain C) VR.
    Comment for a chance to win spins!"
  agent: marketing_agent

# Customer support Agent Task
customer_support_task:
  description: >
    Monitor the group for common questions or issues related to {topic} or platform use.
    Provide quick, concise answers, acknowledge feedback, and encourage further interaction.
  expected_output: >
    Immediate responses like, "Need help with your treasure code? DM us or check our FAQ!"
    or messages like, "Thanks for your feedback on {topic}! We're always improving.
    More updates coming soon!"
  agent: customer_service_agent
